version: '2'
services:
   synapse:
      build:
         context: ./build/docker-synapse
         dockerfile: Dockerfile
         args:
            username: "synapse"
      image: synapse:latest
      command: python -B -m synapse.app.homeserver -c ./config/homeserver.yaml
      ports:
         - "8448:8448"
      volumes:
         - "./run/config:/home/synapse/config"
         - "./run/register-user.sh:/home/synapse/register-user.sh"

